### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Miskuzi-d** [Tyson3101/Auto-TikTok-Scroller#2]
When I use Bookmarklet this error crashes
![image](https://user-images.githubusercontent.com/55347537/149021085-9c0bb4fe-e44a-4c9b-b704-347de1f1d149.png)

**Comment by Tyson3101** [comment]
Thanks for this, thats a really silly error on my part lol, I will try to fix this when I can.

**Comment by Tyson3101** [comment]
Been awhile!! I have updated the extension and have posted it on the chrome web store (should take around 3 days to be published)
