### ISSUE TITLE
Comment side window in full screen mode won't scroll with this extension active.

### ISSUE THREAD

**Issue by VernMcC** [Tyson3101/Auto-TikTok-Scroller#4]
Chrome: Version 107.0.5304.88 (Official Build) (64-bit) on Windows 10 but this has been happening for a while.

When viewing video  in full screen I can use Shift F to open and close comment window, but I cannot scroll in the comments window. The Comment entry box is only visible if there are not enough comments to push it below the bottom of the window.

I tested and if I disable this app the full screen comment side window becomes scrollable with the Comment entry box at the bottom. I disabled all other extensions to test, so base Chrome with this extension and I cannot scroll or enter a comment in the side comment window. When I remove this extension, I can.

I love the extension and work around by refreshing the screen on a video, which changes the view so the comments are at the bottom, and I can enter a comment. But wanted to raise the issue.

**Comment by Tyson3101** [comment]
Hi, sorry just saw this, thanks for bringing this up and I am glad you like the extension!
I looked into this issue and I think I found a way to solve it. It should be updated on the google extension soon. 
And sorry again for the long wait

**Comment by VernMcC** [comment]
Just opened the app with you plugin installed and it is working as expected. Thank you so much for addressing this so quickly.
