### ISSUE TITLE
Publish for Firefox

### ISSUE THREAD

**Issue by ModProg** [Tyson3101/Auto-TikTok-Scroller#6]
The extension works as is in Firefox and it would be great if you could publish it on the Mozilla add-ons store (https://addons.mozilla.org/de/developers/addon/submit/distribution).

If you prefer it, I could also do that.

Edit:
In case anyone is looking for it: https://addons.mozilla.org/en-US/firefox/addon/auto-tiktok-scroller/

**Comment by Tyson3101** [comment]
Yo, that would be great if you are able to do so
Someone forked my [Auto Shorts Scroller](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller) and uploaded it on the Firefox addon store I have no issues with you doing it as well.

I also doubt I will add to this anymore, so you won't need to worry about any updates/changes, and you can add your own features if you do want.

So yeah if you can then go ahead, thanks.

**Comment by Tyson3101** [comment]
But if you do need/want me to, then I can have a go

**Comment by ModProg** [comment]
would you mind adding a license that would actually allow me to do it? 

https://github.com/Tyson3101/Auto-TikTok-Scroller/community/license/new?branch=main&filename=LICENSE&template=apache-2.0

**Comment by Tyson3101** [comment]
Oh yep no problem, thanks for the link
